logger:
  mode: dev
  log-format: json
  log-level: debug
  datetime-format: "2006-01-02 15:04:05"
  use-timestamp: false
  include-caller-method: true

delivery:
  http-server:
    log-requests: true
    listen-address: 0.0.0.0:40004
    read-timeout: 100s
    write-timeout: 100s
    body-size-limit: 10128
    graceful-timeout: 60

authorization-service:
  url: "http://authenticator-service:40003/v1/authenticator/auth"

proxy:
  - enabled: true
    group: "/user/profile"
    routes:
    - in: "/"
      to: "http://user-service:40002/v1/user/user/profile"
      method: "GET"
      check-authorization: true
  - enabled: true
    group: "/microservice/name"
    routes:
    - in: "/"
      to: "http://user-service:40002/v1/user/microservice/name"
      method: "GET"
      check-authorization: false
